services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/certs:ro
      - ./nginx/certs/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./nginx/html:/etc/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./jellyfin:/config
      - /mnt/media:/media
    ports:
      - "8096:8096"
    restart: unless-stopped
    labels:
      - autoheal=true

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "0.0.0.0:9091:9091/tcp" # Transmission
    volumes:
      - ./gluetun:/gluetun
    environment:
      - TZ=Europe/London
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=ivpn
      - VPN_TYPE=wireguard
      # OpenVPN:
      #- OPENVPN_USER=
      #- OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=${wireguard_private_key}
      - WIREGUARD_ADDRESSES=${wireguard_addresses}
      - SERVER_COUNTRIES=${wireguard_server_countries}
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
    restart: unless-stopped
    labels:
      - autoheal=true

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - USER=${transmission_user}
      - PASS=${transmission_pass}
    volumes:
      - ./transmission:/config
      - /mnt/media/downloads:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    healthcheck:
      test: ["CMD-SHELL", "transmission-remote --auth $$USER:$$PASS -l >/dev/null 2>&1 || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL --max-time 5 http://localhost:8191/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true
      - RUN_OPTS=
    volumes:
      - ./jackett:/config
      - /mnt/media/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9117/UI/Dashboard || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SONARR_API_KEY=${sonarr_api_key}
    ports:
      - "8989:8989"
    volumes:
      - ./sonarr:/config
      - /mnt/media:/media
      - /mnt/media/downloads:/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL --max-time 5 -H \"X-Api-Key: $$SONARR_API_KEY\" http://localhost:8989/api/v3/system/status || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - RADARR_API_KEY=${radarr_api_key}
    ports:
      - "7878:7878"
    volumes:
      - ./radarr:/config
      - /mnt/media:/media
      - /mnt/media/downloads:/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL --max-time 5 -H \"X-Api-Key: $$RADARR_API_KEY\" http://localhost:7878/api/v3/system/status || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/London
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * 0
    restart: unless-stopped
    labels:
      - autoheal=true

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=60
      - WEBHOOK_URL="" # Add a webhook if needed
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: none