#!/bin/bash
vpnclient=""
vpnname=""
relaydomain=""
destinationemail=""
authuser=""
authpassword=""

# Usage
print_usage() {
    printf "Usage: gen-ovpn -v [client name] -V [vpn server name] -r [relay server] -e [destination email]
    Port 587 will be used if a username AND password is provided to authenticate with the smtp relay, otherwise port 25 is used without authentication.
    Non-authenticated smtp requests will likely be denied unless the IP it is being sent from is whitelisted.

    -v    Name given to the client .ovpn profile and associated certificates e.g. client1
    -V    Friendly name of the VPN server e.g. PersonalVPN
    -r    Name of the mail server that will act as the smtp relay to send the profile email
    -a    Name used to authenticate with the smtp relay (optional)
    -p    Password used to authenticate with the smtp relay (optional)
    -d    The email address the .ovpn profile should be sent to
    -h    Prints these instructions
"
}

# Flags
while getopts 'v:V:r:d:a:p:h' flag; do
    case "${flag}" in
        v) vpnclient="${OPTARG}" ;;
        V) vpnname="${OPTARG}" ;;
        r) relaydomain="${OPTARG}" ;;
        d) destinationemail="${OPTARG}" ;;
        a) authuser="${OPTARG}" ;;
        p) authpassword="${OPTARG}" ;;
        h) print_usage
           exit 0 ;;
        *) print_usage
           exit 1 ;;
    esac
done

if [[ -z "$vpnclient" && -z "$vpnname" && -z "$relaydomain" && -z "$destinationemail" ]]; then
    echo "A client name, VPN name, relay domain and destination email address must be specified."; echo ""
    exit 1
fi

cd /etc/easy-rsa || return
./easyrsa gen-req "$vpnclient" nopass
./easyrsa sign-req client "$vpnclient"
cp /etc/openvpn/template-profiles/profile.ovpn /etc/openvpn/client-profiles/"$vpnclient".ovpn
{
    echo -e " \n<ca>"
    cat /etc/openvpn/server/ca.crt
    echo -e "</ca>\n<cert>"
    cat /etc/easy-rsa/pki/issued/"$vpnclient".crt
    echo -e "</cert>\n<key>"
    cat /etc/easy-rsa/pki/private/"$vpnclient".key
    echo -e "</key>\n<tls-auth>"
    cat /etc/openvpn/server/ta.key
    echo "</tls-auth>"
} >>/etc/openvpn/client-profiles/"$vpnclient".ovpn

if [[ -n "$authuser" && -z "$authpassword" ]]; then
    echo -e "Hello, \n Here is your requested OVPN profile for $vpnname." \
        | mailx -v -s "$vpnname OVPN Profile" \
        -S smtp-use-starttls \
        -S ssl-verify=ignore \
        -S smtp-auth=login \
        -S smtp=smtp://$relaydomain:587 \
        -S from="no-reply@$relaydomain($vpnname)" \
        -S smtp-auth-user=$authuser \
        -S smtp-auth-password=$authpassword \
        -S ssl-verify=ignore \
        -S nss-config-dir=~/etc/pki/nssdb/ \
        $destinationemail
else
    echo -e "Hello, \n Here is your requested OVPN profile for $vpnname." \
        | mailx  -s "$vpnname OVPN Profile" \
        -S smtp=smtp://$relaydomain:25 \
        -S from="no-reply@$relaydomain($vpnname)" \
        -a /etc/openvpn/client-profiles/$vpnclient.ovpn \
        $destinationemail
fi
